apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: pose-microservices
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: pose-microservices
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: tcp
    port: 3001
    targetPort: 3001
    protocol: TCP
  - name: metrics
    port: 9101
    targetPort: 9101
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: item-service
  namespace: pose-microservices
  labels:
    app: item-service
spec:
  selector:
    app: item-service
  ports:
  - name: tcp
    port: 3002
    targetPort: 3002
    protocol: TCP
  - name: http
    port: 3009
    targetPort: 3009
    protocol: TCP
  - name: metrics
    port: 9102
    targetPort: 9102
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: pose-microservices
  labels:
    app: email-service
spec:
  selector:
    app: email-service
  ports:
  - name: tcp
    port: 3003
    targetPort: 3003
    protocol: TCP
  - name: metrics
    port: 9103
    targetPort: 9103
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: category-service
  namespace: pose-microservices
  labels:
    app: category-service
spec:
  selector:
    app: category-service
  ports:
  - name: tcp
    port: 3004
    targetPort: 3004
    protocol: TCP
  - name: metrics
    port: 9105
    targetPort: 9105
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: medical-supplies-service
  namespace: pose-microservices
  labels:
    app: medical-supplies-service
spec:
  selector:
    app: medical-supplies-service
  ports:
  - name: tcp
    port: 3008
    targetPort: 3008
    protocol: TCP
  - name: metrics
    port: 9108
    targetPort: 9108
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: pose-microservices
  labels:
    app: report-service
spec:
  selector:
    app: report-service
  ports:
  - name: tcp
    port: 3006
    targetPort: 3006
    protocol: TCP
  - name: metrics
    port: 9106
    targetPort: 9106
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: department-service
  namespace: pose-microservices
  labels:
    app: department-service
spec:
  selector:
    app: department-service
  ports:
  - name: tcp
    port: 3011
    targetPort: 3011
    protocol: TCP
  - name: metrics
    port: 9111
    targetPort: 9111
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: pose-microservices
  labels:
    app: gateway-api
  annotations:
    metallb.universe.tf/allow-shared-ip: "pose-services"
spec:
  selector:
    app: gateway-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer

